# Generated by Django 5.0 on 2026-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theme',
            field=models.JSONField(blank=True, default=dict, help_text='Surcharge du thème par défaut (couleurs, polices, tailles)', verbose_name='Thème personnalisé'),
        ),
    ]
