# Generated by Django 5.0 on 2026-04-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('director', 'Directeur'), ('manager', 'Manager'), ('viewer', 'Lecteur')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='Service / Département')),
                ('role', models.CharField(choices=[('service_manager', 'Responsable de service'), ('service_viewer', 'Membre du service')], default='service_viewer', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de service',
                'verbose_name_plural': 'Membres de service',
                'unique_together': {('user', 'organization', 'service')},
            },
        ),
    ]
