# Generated by Django 5.0 on 2026-04-17 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service / Département')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='organizations.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procédure',
                'verbose_name_plural': 'Procédures',
                'ordering': ['organization', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description du changement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Demande de changement',
                'verbose_name_plural': 'Demandes de changement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_optim', models.FloatField(default=0.0, verbose_name="Score d'optimisation")),
                ('score_auto', models.FloatField(default=0.0, verbose_name="Score d'automatisation")),
                ('anomalies', models.JSONField(default=list, verbose_name='Anomalies détectées')),
                ('recommendations', models.JSONField(default=list, verbose_name='Recommandations')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='procedures.procedure')),
            ],
            options={
                'verbose_name': "Rapport d'audit",
                'verbose_name_plural': "Rapports d'audit",
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Intitulé de la règle')),
                ('condition', models.TextField(help_text='Ex: Toute dépense > 500€ nécessite deux signatures', verbose_name='Condition')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('blocking', 'Bloquant')], default='warning', max_length=20)),
                ('legal_ref', models.CharField(blank=True, help_text='Ex: Art. L1237-19 Code du Travail', max_length=255, verbose_name='Référence légale')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Règle',
                'verbose_name_plural': 'Règles',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'étape")),
                ('action_verb', models.CharField(help_text='Ex: saisir, valider, envoyer, copier', max_length=100, verbose_name="Verbe d'action")),
                ('actor_role', models.CharField(help_text='Ex: Comptable, DG, RH', max_length=100, verbose_name="Rôle de l'acteur")),
                ('tool_used', models.CharField(blank=True, help_text='Ex: Excel, SAP, Email', max_length=100, verbose_name='Outil utilisé')),
                ('estimated_duration', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (min)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tâche récurrente')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Automatique'), ('timer', 'Planifié')], default='manual', max_length=20)),
                ('has_condition', models.BooleanField(default=False, verbose_name='Contient un Si/Alors')),
                ('output_type', models.CharField(choices=[('document', 'Document'), ('data', 'Données'), ('decision', 'Décision'), ('none', 'Aucun')], default='none', max_length=20)),
                ('automation_score', models.FloatField(default=0.0, verbose_name="Score d'automatisation")),
                ('compliance_status', models.CharField(choices=[('compliant', 'Conforme'), ('warning', 'À vérifier'), ('non_compliant', 'Non conforme')], default='warning', max_length=20)),
                ('step_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='procedures.step')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['procedure', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='StepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_label', models.CharField(blank=True, help_text='Ex: Si approuvé, Si montant > 500€', max_length=255, verbose_name='Condition')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_out', to='procedures.step')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_in', to='procedures.step')),
            ],
            options={
                'verbose_name': 'Dépendance',
                'verbose_name_plural': 'Dépendances',
                'unique_together': {('from_step', 'to_step')},
            },
        ),
    ]
