# Generated by Django 5.0 on 2026-04-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='blocking_rules',
            field=models.JSONField(default=list, verbose_name='Règles bloquantes détectées'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='workflow_log',
            field=models.JSONField(default=list, verbose_name='Journal du workflow'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Soumis'), ('auto_checking', 'Analyse automatique en cours'), ('auto_rejected', 'Rejeté automatiquement'), ('awaiting_review', 'En attente de validation'), ('approved', 'Approuvée'), ('auto_approved', 'Approuvée automatiquement'), ('rejected', 'Rejetée')], default='pending', max_length=30),
        ),
    ]
