# Generated by Django 5.0 on 2026-04-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_changerequest_blocking_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(choices=[('patch', "Correctif (patch) — ex: reformulation, ajout d'outil"), ('minor', "Mineur — ex: ajout d'étape, modification d'acteur"), ('major', 'Majeur — ex: refonte structurelle, changement légal')], default='patch', max_length=10, verbose_name='Type de changement'),
        ),
    ]
