# Generated by Django 5.0 on 2026-04-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_changerequest_change_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivée le'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Archivée par'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='procedures.procedure', verbose_name='Version parente'),
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='Numéro de version')),
                ('snapshot_data', models.JSONField(verbose_name='Données de la procédure')),
                ('change_summary', models.TextField(blank=True, verbose_name='Résumé des changements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('auto_approval', 'Approbation automatique'), ('manual_archive', 'Archivage manuel')], default='auto_approval', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Version de procédure',
                'verbose_name_plural': 'Versions de procédures',
                'ordering': ['-created_at'],
                'unique_together': {('procedure', 'version_number')},
            },
        ),
    ]
